import { Question, Test, User, TestAttempt } from '../types';

export const DEMO_TEACHER: User = {
  id: 'teacher-arthur',
  name: 'Dr. Arthur Vance',
  email: 'teacher@testifyme.edu',
  role: 'teacher',
  createdAt: Date.now() - 30 * 24 * 3600 * 1000,
};

export const DEMO_STUDENTS: User[] = [
  { id: 'stu-1', name: 'Aarav Sharma', email: 'aarav@testifyme.edu', role: 'student', studentId: 'STU-2026-001', createdAt: Date.now() - 10 * 86400000 },
  { id: 'stu-2', name: 'Maya Patel', email: 'maya@testifyme.edu', role: 'student', studentId: 'STU-2026-002', createdAt: Date.now() - 10 * 86400000 },
  { id: 'stu-3', name: 'Liam Chen', email: 'liam@testifyme.edu', role: 'student', studentId: 'STU-2026-003', createdAt: Date.now() - 10 * 86400000 },
  { id: 'stu-4', name: 'Sophia Davis', email: 'sophia@testifyme.edu', role: 'student', studentId: 'STU-2026-004', createdAt: Date.now() - 10 * 86400000 },
  { id: 'stu-5', name: 'Rohan Gupta', email: 'rohan@testifyme.edu', role: 'student', studentId: 'STU-2026-005', createdAt: Date.now() - 10 * 86400000 },
  { id: 'stu-6', name: 'Lucas Walker', email: 'lucas@testifyme.edu', role: 'student', studentId: 'STU-2026-006', createdAt: Date.now() - 10 * 86400000 },
  { id: 'stu-7', name: 'Emma Watson', email: 'emma@testifyme.edu', role: 'student', studentId: 'STU-2026-007', createdAt: Date.now() - 10 * 86400000 },
  { id: 'stu-8', name: 'Ethan Taylor', email: 'ethan@testifyme.edu', role: 'student', studentId: 'STU-2026-008', createdAt: Date.now() - 10 * 86400000 },
  { id: 'stu-9', name: 'Oliver Kim', email: 'oliver@testifyme.edu', role: 'student', studentId: 'STU-2026-009', createdAt: Date.now() - 10 * 86400000 },
  { id: 'stu-10', name: 'Zoe Martinez', email: 'zoe@testifyme.edu', role: 'student', studentId: 'STU-2026-010', createdAt: Date.now() - 10 * 86400000 },
];

export const ASSERTION_REASON_OPTIONS = [
  { id: 'A', text: 'Both Assertion and Reason are true, and Reason is the correct explanation of Assertion.' },
  { id: 'B', text: 'Both Assertion and Reason are true, but Reason is not the correct explanation of Assertion.' },
  { id: 'C', text: 'Assertion is true, but Reason is false.' },
  { id: 'D', text: 'Assertion is false, but Reason is true.' },
];

// 100 Realistic Educational Questions (Science, Chemistry, Physics, Math, Biology)
export const DEMO_QUESTIONS: Question[] = [
  // 6 Assertion-Reason Questions (>= 5 guaranteed)
  {
    id: 'q-ar-1',
    type: 'ASSERTION_REASON',
    questionText: 'Assertion-Reason: Acid Rain and Atmospheric Chemistry',
    assertion: 'Acid rain causes extensive corrosion of marble monuments such as the Taj Mahal.',
    reason: 'Sulphuric acid in acid rain reacts with calcium carbonate (marble) to form calcium sulphate, water, and carbon dioxide.',
    options: ASSERTION_REASON_OPTIONS,
    correctAnswer: 'A',
    marks: 1,
    explanation: 'Calcium carbonate reacts with sulphuric acid: CaCO3 + H2SO4 -> CaSO4 + H2O + CO2, causing pitting and yellowing of marble.',
    subject: 'Chemistry',
    chapter: 'Environmental Chemistry',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 100000,
  },
  {
    id: 'q-ar-2',
    type: 'ASSERTION_REASON',
    questionText: 'Assertion-Reason: Diamond and Graphite Electrical Conductivity',
    assertion: 'Diamond is an electrical insulator while graphite is a good electrical conductor.',
    reason: 'In diamond, all 4 valence electrons of carbon participate in covalent bonding, whereas in graphite each carbon bonds with only 3 others, leaving free delocalized pi electrons.',
    options: ASSERTION_REASON_OPTIONS,
    correctAnswer: 'A',
    marks: 1,
    explanation: 'Delocalized pi electrons in graphite layer sheets allow electrical conduction along the planes.',
    subject: 'Chemistry',
    chapter: 'Chemical Bonding & Solid State',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 95000,
  },
  {
    id: 'q-ar-3',
    type: 'ASSERTION_REASON',
    questionText: 'Assertion-Reason: Electric Current in Conductors',
    assertion: 'When a wire carrying current is placed in an electric circuit, the wire remains electrically neutral as a whole.',
    reason: 'For every electron entering one end of the conductor, an electron leaves the other end per unit time.',
    options: ASSERTION_REASON_OPTIONS,
    correctAnswer: 'A',
    marks: 1,
    explanation: 'Steady current maintains constant charge density within the conductor, so net charge remains zero.',
    subject: 'Physics',
    chapter: 'Current Electricity',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 90000,
  },
  {
    id: 'q-ar-4',
    type: 'ASSERTION_REASON',
    questionText: 'Assertion-Reason: Photosynthesis & Light Reactions',
    assertion: 'Chlorophyll looks green to the human eye.',
    reason: 'Chlorophyll molecules preferentially absorb green wavelengths of sunlight and reflect red and blue light.',
    options: ASSERTION_REASON_OPTIONS,
    correctAnswer: 'C',
    marks: 1,
    explanation: 'Assertion is true, but Reason is false: chlorophyll absorbs blue and red wavelengths and reflects/transmits green light.',
    subject: 'Biology',
    chapter: 'Photosynthesis',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 85000,
  },
  {
    id: 'q-ar-5',
    type: 'ASSERTION_REASON',
    questionText: 'Assertion-Reason: Projectile Motion',
    assertion: 'At the highest point of a projectile’s trajectory, its velocity is zero.',
    reason: 'The vertical component of projectile velocity becomes zero at the highest point under constant downward gravity.',
    options: ASSERTION_REASON_OPTIONS,
    correctAnswer: 'D',
    marks: 1,
    explanation: 'Assertion is false because the horizontal velocity component remains non-zero (u cos theta). Reason is true.',
    subject: 'Physics',
    chapter: 'Kinematics',
    difficulty: 'hard',
    active: true,
    createdAt: Date.now() - 80000,
  },
  {
    id: 'q-ar-6',
    type: 'ASSERTION_REASON',
    questionText: 'Assertion-Reason: Inert Gas Reactivity',
    assertion: 'Noble gases form very few chemical compounds.',
    reason: 'Noble gases possess completely filled outer valence electron shells, giving them high ionization enthalpies and positive electron gain enthalpies.',
    options: ASSERTION_REASON_OPTIONS,
    correctAnswer: 'A',
    marks: 1,
    explanation: 'The octet electronic configuration imparts exceptional thermodynamic stability.',
    subject: 'Chemistry',
    chapter: 'Periodic Table & Elements',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 75000,
  },

  // 94 Real Standard MCQs across Chemistry, Physics, Biology, Math, Computer Science
  // Chemistry (25 Questions)
  {
    id: 'q-ch-1',
    type: 'MCQ',
    questionText: 'What is the pH of a neutral aqueous solution at 25°C?',
    options: [
      { id: 'A', text: '0' },
      { id: 'B', text: '7' },
      { id: 'C', text: '14' },
      { id: 'D', text: '1' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Acids and Bases',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 70000,
  },
  {
    id: 'q-ch-2',
    type: 'MCQ',
    questionText: 'Which orbital hybridization is present in the methane (CH₄) molecule?',
    options: [
      { id: 'A', text: 'sp' },
      { id: 'B', text: 'sp²' },
      { id: 'C', text: 'sp³' },
      { id: 'D', text: 'dsp²' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Chemical Bonding',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 69000,
  },
  {
    id: 'q-ch-3',
    type: 'MCQ',
    questionText: 'According to Le Chatelier’s principle, what happens to the exothermic Haber process (N₂ + 3H₂ ⇌ 2NH₃ + heat) when temperature is increased?',
    options: [
      { id: 'A', text: 'Equilibrium shifts toward ammonia product' },
      { id: 'B', text: 'Equilibrium shifts toward reactants N₂ and H₂' },
      { id: 'C', text: 'No change in equilibrium position occurs' },
      { id: 'D', text: 'Total pressure drops to zero' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Chemical Equilibrium',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 68000,
  },
  {
    id: 'q-ch-4',
    type: 'MCQ',
    questionText: 'Which of the following transition metals exhibits the highest common oxidation state (+7)?',
    options: [
      { id: 'A', text: 'Iron (Fe)' },
      { id: 'B', text: 'Manganese (Mn)' },
      { id: 'C', text: 'Chromium (Cr)' },
      { id: 'D', text: 'Copper (Cu)' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'd-Block Elements',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 67000,
  },
  {
    id: 'q-ch-5',
    type: 'MCQ',
    questionText: 'What is the conjugate base of hydrogen sulphate ion (HSO₄⁻)?',
    options: [
      { id: 'A', text: 'H₂SO₄' },
      { id: 'B', text: 'SO₄²⁻' },
      { id: 'C', text: 'SO₃²⁻' },
      { id: 'D', text: 'H₃O⁺' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Ionic Equilibrium',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 66000,
  },
  {
    id: 'q-ch-6',
    type: 'MCQ',
    questionText: 'What is the oxidation number of sulfur in H₂SO₄?',
    options: [
      { id: 'A', text: '+4' },
      { id: 'B', text: '+6' },
      { id: 'C', text: '-2' },
      { id: 'D', text: '+2' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Redox Reactions',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 65000,
  },
  {
    id: 'q-ch-7',
    type: 'MCQ',
    questionText: 'Which gas law states that at constant pressure, the volume of a given mass of gas is directly proportional to its absolute temperature?',
    options: [
      { id: 'A', text: 'Boyle’s Law' },
      { id: 'B', text: 'Charles’s Law' },
      { id: 'C', text: 'Avogadro’s Law' },
      { id: 'D', text: 'Gay-Lussac’s Law' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'States of Matter',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 64000,
  },
  {
    id: 'q-ch-8',
    type: 'MCQ',
    questionText: 'Which of the following compounds exhibits optical isomerism (chirality)?',
    options: [
      { id: 'A', text: '2-Chlorobutane' },
      { id: 'B', text: '1-Chlorobutane' },
      { id: 'C', text: 'Propane' },
      { id: 'D', text: 'Ethanol' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Organic Chemistry',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 63000,
  },
  {
    id: 'q-ch-9',
    type: 'MCQ',
    questionText: 'What is the catalyst commonly used in the hydrogenation of unsaturated vegetable oils?',
    options: [
      { id: 'A', text: 'Iron (Fe)' },
      { id: 'B', text: 'Finely divided Nickel (Ni)' },
      { id: 'C', text: 'Vanadium pentoxide (V₂O₅)' },
      { id: 'D', text: 'Aluminium chloride (AlCl₃)' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Surface Chemistry',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 62000,
  },
  {
    id: 'q-ch-10',
    type: 'MCQ',
    questionText: 'Which aqueous solution will have the highest boiling point elevation at 1 atm?',
    options: [
      { id: 'A', text: '0.1 M Glucose' },
      { id: 'B', text: '0.1 M NaCl' },
      { id: 'C', text: '0.1 M BaCl₂' },
      { id: 'D', text: '0.1 M Urea' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Solutions',
    difficulty: 'hard',
    active: true,
    createdAt: Date.now() - 61000,
  },
  {
    id: 'q-ch-11',
    type: 'MCQ',
    questionText: 'Which halogen is a reddish-brown liquid at standard room temperature and pressure?',
    options: [
      { id: 'A', text: 'Fluorine' },
      { id: 'B', text: 'Chlorine' },
      { id: 'C', text: 'Bromine' },
      { id: 'D', text: 'Iodine' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'p-Block Elements',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 60000,
  },
  {
    id: 'q-ch-12',
    type: 'MCQ',
    questionText: 'What is the rate law for a zero-order chemical reaction A -> Products?',
    options: [
      { id: 'A', text: 'Rate = k[A]' },
      { id: 'B', text: 'Rate = k' },
      { id: 'C', text: 'Rate = k[A]²' },
      { id: 'D', text: 'Rate = k / [A]' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Chemical Kinetics',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 59000,
  },
  {
    id: 'q-ch-13',
    type: 'MCQ',
    questionText: 'In electrolytic cells, at which electrode does reduction always take place?',
    options: [
      { id: 'A', text: 'Cathode' },
      { id: 'B', text: 'Anode' },
      { id: 'C', text: 'Salt bridge' },
      { id: 'D', text: 'Voltmeter terminal' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Electrochemistry',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 58000,
  },
  {
    id: 'q-ch-14',
    type: 'MCQ',
    questionText: 'What is the primary product of the reaction between an alcohol and a carboxylic acid in presence of concentrated H₂SO₄?',
    options: [
      { id: 'A', text: 'Aldehyde' },
      { id: 'B', text: 'Ether' },
      { id: 'C', text: 'Ester' },
      { id: 'D', text: 'Ketone' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Organic Compounds',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 57000,
  },
  {
    id: 'q-ch-15',
    type: 'MCQ',
    questionText: 'Which element has the highest first ionization energy across the periodic table?',
    options: [
      { id: 'A', text: 'Hydrogen' },
      { id: 'B', text: 'Helium' },
      { id: 'C', text: 'Fluorine' },
      { id: 'D', text: 'Neon' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Periodic Classification',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 56000,
  },
  {
    id: 'q-ch-16',
    type: 'MCQ',
    questionText: 'What is the shape of a water (H₂O) molecule according to VSEPR theory?',
    options: [
      { id: 'A', text: 'Linear' },
      { id: 'B', text: 'Trigonal planar' },
      { id: 'C', text: 'Bent (V-shaped)' },
      { id: 'D', text: 'Tetrahedral' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Chemical Bonding',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 55000,
  },
  {
    id: 'q-ch-17',
    type: 'MCQ',
    questionText: 'Which of the following is an example of a condensation polymer?',
    options: [
      { id: 'A', text: 'Polyethylene' },
      { id: 'B', text: 'Nylon-6,6' },
      { id: 'C', text: 'Polytetrafluoroethylene (Teflon)' },
      { id: 'D', text: 'Polystyrene' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Polymers',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 54000,
  },
  {
    id: 'q-ch-18',
    type: 'MCQ',
    questionText: 'What is the IUPAC name for acetone (CH₃COCH₃)?',
    options: [
      { id: 'A', text: 'Propanal' },
      { id: 'B', text: 'Propan-2-one' },
      { id: 'C', text: 'Ethanone' },
      { id: 'D', text: 'Propan-1-ol' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Organic Nomenclature',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 53000,
  },
  {
    id: 'q-ch-19',
    type: 'MCQ',
    questionText: 'What is the unit of molarity for a chemical solution?',
    options: [
      { id: 'A', text: 'mol / kg' },
      { id: 'B', text: 'mol / L' },
      { id: 'C', text: 'g / L' },
      { id: 'D', text: 'mol / mol' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Basic Concepts of Chemistry',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 52000,
  },
  {
    id: 'q-ch-20',
    type: 'MCQ',
    questionText: 'Which gas is evolved when zinc metal reacts with dilute hydrochloric acid?',
    options: [
      { id: 'A', text: 'Oxygen' },
      { id: 'B', text: 'Chlorine' },
      { id: 'C', text: 'Hydrogen' },
      { id: 'D', text: 'Carbon dioxide' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Chemical Reactions',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 51000,
  },
  {
    id: 'q-ch-21',
    type: 'MCQ',
    questionText: 'Which law relates the partial pressure of a gas above a liquid to its mole fraction in solution?',
    options: [
      { id: 'A', text: 'Henry’s Law' },
      { id: 'B', text: 'Dalton’s Law' },
      { id: 'C', text: 'Raoult’s Law' },
      { id: 'D', text: 'Graham’s Law' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Solutions',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 50000,
  },
  {
    id: 'q-ch-22',
    type: 'MCQ',
    questionText: 'What is the color of copper sulfate crystals (CuSO₄·5H₂O)?',
    options: [
      { id: 'A', text: 'Green' },
      { id: 'B', text: 'Blue' },
      { id: 'C', text: 'White' },
      { id: 'D', text: 'Yellow' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Coordination Chemistry',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 49000,
  },
  {
    id: 'q-ch-23',
    type: 'MCQ',
    questionText: 'What is the primary greenhouse gas released by human fossil fuel combustion?',
    options: [
      { id: 'A', text: 'Methane' },
      { id: 'B', text: 'Carbon dioxide' },
      { id: 'C', text: 'Ozone' },
      { id: 'D', text: 'Nitrous oxide' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Environmental Chemistry',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 48000,
  },
  {
    id: 'q-ch-24',
    type: 'MCQ',
    questionText: 'Which process describes the direct phase transition from solid to gas without entering the liquid state?',
    options: [
      { id: 'A', text: 'Evaporation' },
      { id: 'B', text: 'Condensation' },
      { id: 'C', text: 'Sublimation' },
      { id: 'D', text: 'Deposition' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'States of Matter',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 47000,
  },
  {
    id: 'q-ch-25',
    type: 'MCQ',
    questionText: 'What is the formal charge on the central oxygen atom in an ozone (O₃) resonance structure?',
    options: [
      { id: 'A', text: '0' },
      { id: 'B', text: '+1' },
      { id: 'C', text: '-1' },
      { id: 'D', text: '+2' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Chemistry',
    chapter: 'Chemical Bonding',
    difficulty: 'hard',
    active: true,
    createdAt: Date.now() - 46000,
  },

  // Physics (25 Questions)
  {
    id: 'q-ph-1',
    type: 'MCQ',
    questionText: 'What is the SI unit of electric capacitance?',
    options: [
      { id: 'A', text: 'Henry' },
      { id: 'B', text: 'Farad' },
      { id: 'C', text: 'Tesla' },
      { id: 'D', text: 'Weber' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Physics',
    chapter: 'Electrostatics',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 45000,
  },
  {
    id: 'q-ph-2',
    type: 'MCQ',
    questionText: 'A body moves in a circular path of radius R with constant speed v. What is the magnitude of its centripetal acceleration?',
    options: [
      { id: 'A', text: 'v / R' },
      { id: 'B', text: 'v² / R' },
      { id: 'C', text: 'v² R' },
      { id: 'D', text: 'v / R²' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Physics',
    chapter: 'Circular Motion',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 44000,
  },
  {
    id: 'q-ph-3',
    type: 'MCQ',
    questionText: 'Which optical phenomenon explains the shimmering mirage seen on hot desert highways?',
    options: [
      { id: 'A', text: 'Total Internal Reflection' },
      { id: 'B', text: 'Diffraction' },
      { id: 'C', text: 'Polarization' },
      { id: 'D', text: 'Photoelectric effect' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Physics',
    chapter: 'Ray Optics',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 43000,
  },
  {
    id: 'q-ph-4',
    type: 'MCQ',
    questionText: 'What happens to the frequency of a sound wave as it travels from air into water?',
    options: [
      { id: 'A', text: 'It increases' },
      { id: 'B', text: 'It decreases' },
      { id: 'C', text: 'It remains unchanged' },
      { id: 'D', text: 'It drops to zero' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Physics',
    chapter: 'Wave Mechanics',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 42000,
  },
  {
    id: 'q-ph-5',
    type: 'MCQ',
    questionText: 'What is the work done by the gravitational force on an object during a complete circular orbit around the Earth?',
    options: [
      { id: 'A', text: '2 * pi * G * M * m' },
      { id: 'B', text: 'Zero' },
      { id: 'C', text: 'G * M * m / R²' },
      { id: 'D', text: '1/2 m v²' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Physics',
    chapter: 'Work, Power & Energy',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 41000,
  },
  {
    id: 'q-ph-6',
    type: 'MCQ',
    questionText: 'Which fundamental law of thermodynamics establishes the concept of entropy?',
    options: [
      { id: 'A', text: 'Zeroth Law' },
      { id: 'B', text: 'First Law' },
      { id: 'C', text: 'Second Law' },
      { id: 'D', text: 'Third Law' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Physics',
    chapter: 'Thermodynamics',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 40000,
  },
  {
    id: 'q-ph-7',
    type: 'MCQ',
    questionText: 'What is the dimensional formula for Planck’s constant (h)?',
    options: [
      { id: 'A', text: '[M L² T⁻¹]' },
      { id: 'B', text: '[M L² T⁻²]' },
      { id: 'C', text: '[M L T⁻¹]' },
      { id: 'D', text: '[M L² T⁻³]' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Physics',
    chapter: 'Units and Measurements',
    difficulty: 'hard',
    active: true,
    createdAt: Date.now() - 39000,
  },
  {
    id: 'q-ph-8',
    type: 'MCQ',
    questionText: 'Two resistors of 6 ohms and 3 ohms are connected in parallel. What is their equivalent resistance?',
    options: [
      { id: 'A', text: '9 ohms' },
      { id: 'B', text: '2 ohms' },
      { id: 'C', text: '4.5 ohms' },
      { id: 'D', text: '1 ohm' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Physics',
    chapter: 'Current Electricity',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 38000,
  },
  {
    id: 'q-ph-9',
    type: 'MCQ',
    questionText: 'In photoelectric emission, the kinetic energy of emitted photoelectrons depends strictly on:',
    options: [
      { id: 'A', text: 'Intensity of incident light' },
      { id: 'B', text: 'Frequency of incident light' },
      { id: 'C', text: 'Area of metal plate' },
      { id: 'D', text: 'Duration of light exposure' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Physics',
    chapter: 'Dual Nature of Radiation',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 37000,
  },
  {
    id: 'q-ph-10',
    type: 'MCQ',
    questionText: 'What is the escape velocity from the surface of Earth (approximate)?',
    options: [
      { id: 'A', text: '9.8 m/s' },
      { id: 'B', text: '11.2 km/s' },
      { id: 'C', text: '3.0 x 10⁸ m/s' },
      { id: 'D', text: '7.9 km/s' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Physics',
    chapter: 'Gravitation',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 36000,
  },
  {
    id: 'q-ph-11',
    type: 'MCQ',
    questionText: 'Which law describes the induced electromotive force in a circuit as equal to the negative rate of change of magnetic flux?',
    options: [
      { id: 'A', text: 'Ampere’s Law' },
      { id: 'B', text: 'Faraday’s Law of Electromagnetic Induction' },
      { id: 'C', text: 'Ohm’s Law' },
      { id: 'D', text: 'Coulomb’s Law' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Physics',
    chapter: 'Electromagnetic Induction',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 35000,
  },
  {
    id: 'q-ph-12',
    type: 'MCQ',
    questionText: 'What is the time period T of a simple pendulum of length L in a gravitational field g?',
    options: [
      { id: 'A', text: '2 * pi * sqrt(g / L)' },
      { id: 'B', text: '2 * pi * sqrt(L / g)' },
      { id: 'C', text: 'pi * sqrt(L * g)' },
      { id: 'D', text: '2 * pi * (L / g)' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Physics',
    chapter: 'Oscillations',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 34000,
  },
  {
    id: 'q-ph-13',
    type: 'MCQ',
    questionText: 'Which electromagnetic wave has the shortest wavelength in the electromagnetic spectrum?',
    options: [
      { id: 'A', text: 'Radio waves' },
      { id: 'B', text: 'Gamma rays' },
      { id: 'C', text: 'Infrared rays' },
      { id: 'D', text: 'Ultraviolet rays' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Physics',
    chapter: 'Electromagnetic Waves',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 33000,
  },
  {
    id: 'q-ph-14',
    type: 'MCQ',
    questionText: 'What type of lens is used to correct myopia (nearsightedness)?',
    options: [
      { id: 'A', text: 'Convex lens' },
      { id: 'B', text: 'Concave lens' },
      { id: 'C', text: 'Cylindrical lens' },
      { id: 'D', text: 'Bifocal lens' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Physics',
    chapter: 'Human Eye & Optical Instruments',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 32000,
  },
  {
    id: 'q-ph-15',
    type: 'MCQ',
    questionText: 'What is the magnetic field B at the center of a circular loop of radius R carrying current I?',
    options: [
      { id: 'A', text: 'mu_0 * I / (2 * R)' },
      { id: 'B', text: 'mu_0 * I / (4 * pi * R)' },
      { id: 'C', text: 'mu_0 * I * R' },
      { id: 'D', text: '2 * mu_0 * I / R' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Physics',
    chapter: 'Magnetic Effects of Current',
    difficulty: 'hard',
    active: true,
    createdAt: Date.now() - 31000,
  },
  {
    id: 'q-ph-16',
    type: 'MCQ',
    questionText: 'In an elastic collision between two isolated particles, which quantity is conserved?',
    options: [
      { id: 'A', text: 'Only linear momentum' },
      { id: 'B', text: 'Only kinetic energy' },
      { id: 'C', text: 'Both linear momentum and kinetic energy' },
      { id: 'D', text: 'Neither linear momentum nor kinetic energy' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Physics',
    chapter: 'Collisions & Momentum',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 30000,
  },
  {
    id: 'q-ph-17',
    type: 'MCQ',
    questionText: 'What is the power rating P of an electrical appliance carrying current I at voltage V?',
    options: [
      { id: 'A', text: 'P = V * I' },
      { id: 'B', text: 'P = V / I' },
      { id: 'C', text: 'P = I / V' },
      { id: 'D', text: 'P = V² * I' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Physics',
    chapter: 'Current Electricity',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 29000,
  },
  {
    id: 'q-ph-18',
    type: 'MCQ',
    questionText: 'Which physical principle underlies the hydraulic lift used in automobile repair shops?',
    options: [
      { id: 'A', text: 'Bernoulli’s Principle' },
      { id: 'B', text: 'Pascal’s Law' },
      { id: 'C', text: 'Archimedes’ Principle' },
      { id: 'D', text: 'Hooke’s Law' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Physics',
    chapter: 'Fluid Mechanics',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 28000,
  },
  {
    id: 'q-ph-19',
    type: 'MCQ',
    questionText: 'A car accelerates uniformly from rest to 20 m/s in 5 seconds. What is its acceleration?',
    options: [
      { id: 'A', text: '2 m/s²' },
      { id: 'B', text: '4 m/s²' },
      { id: 'C', text: '5 m/s²' },
      { id: 'D', text: '10 m/s²' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Physics',
    chapter: 'Kinematics',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 27000,
  },
  {
    id: 'q-ph-20',
    type: 'MCQ',
    questionText: 'What is the speed of light in vacuum (c)?',
    options: [
      { id: 'A', text: '3.0 x 10⁸ m/s' },
      { id: 'B', text: '3.0 x 10⁶ m/s' },
      { id: 'C', text: '3.0 x 10¹⁰ m/s' },
      { id: 'D', text: '1.5 x 10⁸ m/s' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Physics',
    chapter: 'Optics',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 26000,
  },
  {
    id: 'q-ph-21',
    type: 'MCQ',
    questionText: 'What is the terminal velocity of a small spherical ball falling through a viscous fluid proportional to (Stokes’ law)?',
    options: [
      { id: 'A', text: 'Radius r' },
      { id: 'B', text: 'Square of radius r²' },
      { id: 'C', text: 'Cube of radius r³' },
      { id: 'D', text: 'Independent of radius' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Physics',
    chapter: 'Properties of Bulk Matter',
    difficulty: 'hard',
    active: true,
    createdAt: Date.now() - 25000,
  },
  {
    id: 'q-ph-22',
    type: 'MCQ',
    questionText: 'Which law describes how volume flow rate in fluid streamlines relates to pressure drop and velocity increase?',
    options: [
      { id: 'A', text: 'Bernoulli’s theorem' },
      { id: 'B', text: 'Newton’s cooling law' },
      { id: 'C', text: 'Kepler’s second law' },
      { id: 'D', text: 'Snell’s law' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Physics',
    chapter: 'Fluids',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 24000,
  },
  {
    id: 'q-ph-23',
    type: 'MCQ',
    questionText: 'What is the SI unit of magnetic flux density?',
    options: [
      { id: 'A', text: 'Tesla' },
      { id: 'B', text: 'Weber' },
      { id: 'C', text: 'Gauss' },
      { id: 'D', text: 'Ampere-turn' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Physics',
    chapter: 'Magnetism',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 23000,
  },
  {
    id: 'q-ph-24',
    type: 'MCQ',
    questionText: 'What is the half-life of a radioactive sample if its decay constant lambda is 0.693 s⁻¹?',
    options: [
      { id: 'A', text: '0.5 seconds' },
      { id: 'B', text: '1.0 second' },
      { id: 'C', text: '2.0 seconds' },
      { id: 'D', text: '0.693 seconds' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Physics',
    chapter: 'Nuclear Physics',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 22000,
  },
  {
    id: 'q-ph-25',
    type: 'MCQ',
    questionText: 'What is the efficiency of a Carnot heat engine operating between absolute temperatures Thot and Tcold?',
    options: [
      { id: 'A', text: '1 - (Tcold / Thot)' },
      { id: 'B', text: '1 - (Thot / Tcold)' },
      { id: 'C', text: 'Tcold / Thot' },
      { id: 'D', text: '(Thot + Tcold) / Thot' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Physics',
    chapter: 'Thermodynamics',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 21000,
  },

  // Biology (20 Questions)
  {
    id: 'q-bi-1',
    type: 'MCQ',
    questionText: 'Which organelle is often referred to as the powerhouse of the eukaryotic cell?',
    options: [
      { id: 'A', text: 'Golgi apparatus' },
      { id: 'B', text: 'Mitochondrion' },
      { id: 'C', text: 'Ribosome' },
      { id: 'D', text: 'Lysosome' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Biology',
    chapter: 'Cell Structure',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 20000,
  },
  {
    id: 'q-bi-2',
    type: 'MCQ',
    questionText: 'Which nitrogenous base is present in RNA but absent in DNA?',
    options: [
      { id: 'A', text: 'Thymine' },
      { id: 'B', text: 'Uracil' },
      { id: 'C', text: 'Adenine' },
      { id: 'D', text: 'Guanine' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Biology',
    chapter: 'Molecular Basis of Inheritance',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 19000,
  },
  {
    id: 'q-bi-3',
    type: 'MCQ',
    questionText: 'In humans, which endocrine organ secretes the hormone insulin?',
    options: [
      { id: 'A', text: 'Thyroid gland' },
      { id: 'B', text: 'Pancreas (Islets of Langerhans)' },
      { id: 'C', text: 'Adrenal cortex' },
      { id: 'D', text: 'Pituitary gland' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Biology',
    chapter: 'Endocrine System',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 18000,
  },
  {
    id: 'q-bi-4',
    type: 'MCQ',
    questionText: 'What is the typical phenotypic ratio in the F2 generation of a Mendelian monohybrid cross?',
    options: [
      { id: 'A', text: '1:2:1' },
      { id: 'B', text: '3:1' },
      { id: 'C', text: '9:3:3:1' },
      { id: 'D', text: '1:1:1:1' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Biology',
    chapter: 'Principles of Genetics',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 17000,
  },
  {
    id: 'q-bi-5',
    type: 'MCQ',
    questionText: 'Which enzyme is responsible for synthesizing mRNA from a DNA template during transcription?',
    options: [
      { id: 'A', text: 'DNA Polymerase III' },
      { id: 'B', text: 'RNA Polymerase' },
      { id: 'C', text: 'DNA Ligase' },
      { id: 'D', text: 'Helicase' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Biology',
    chapter: 'Molecular Genetics',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 16000,
  },
  {
    id: 'q-bi-6',
    type: 'MCQ',
    questionText: 'Which blood vessels carry oxygenated blood from the lungs back to the left atrium of the human heart?',
    options: [
      { id: 'A', text: 'Pulmonary arteries' },
      { id: 'B', text: 'Pulmonary veins' },
      { id: 'C', text: 'Superior vena cava' },
      { id: 'D', text: 'Coronary sinus' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Biology',
    chapter: 'Circulatory System',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 15000,
  },
  {
    id: 'q-bi-7',
    type: 'MCQ',
    questionText: 'What is the primary site of water absorption in the human digestive tract?',
    options: [
      { id: 'A', text: 'Stomach' },
      { id: 'B', text: 'Duodenum' },
      { id: 'C', text: 'Large intestine (Colon)' },
      { id: 'D', text: 'Esophagus' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Biology',
    chapter: 'Digestion & Absorption',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 14000,
  },
  {
    id: 'q-bi-8',
    type: 'MCQ',
    questionText: 'Which phase of mitosis is characterized by sister chromatids separating and moving toward opposite poles?',
    options: [
      { id: 'A', text: 'Prophase' },
      { id: 'B', text: 'Metaphase' },
      { id: 'C', text: 'Anaphase' },
      { id: 'D', text: 'Telophase' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Biology',
    chapter: 'Cell Cycle & Cell Division',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 13000,
  },
  {
    id: 'q-bi-9',
    type: 'MCQ',
    questionText: 'What is the basic functional filtering unit of the human kidney?',
    options: [
      { id: 'A', text: 'Neuron' },
      { id: 'B', text: 'Nephron' },
      { id: 'C', text: 'Alveolus' },
      { id: 'D', text: 'Hepatocyte' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Biology',
    chapter: 'Excretory Products & Elimination',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 12000,
  },
  {
    id: 'q-bi-10',
    type: 'MCQ',
    questionText: 'Which plant hormone promotes fruit ripening and senescence?',
    options: [
      { id: 'A', text: 'Auxin' },
      { id: 'B', text: 'Gibberellin' },
      { id: 'C', text: 'Ethylene' },
      { id: 'D', text: 'Cytokinin' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Biology',
    chapter: 'Plant Physiology',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 11000,
  },
  {
    id: 'q-bi-11',
    type: 'MCQ',
    questionText: 'In DNA structure, how many hydrogen bonds form between guanine and cytosine?',
    options: [
      { id: 'A', text: '1' },
      { id: 'B', text: '2' },
      { id: 'C', text: '3' },
      { id: 'D', text: '4' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Biology',
    chapter: 'Biomolecules',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 10000,
  },
  {
    id: 'q-bi-12',
    type: 'MCQ',
    questionText: 'Which ecological interaction benefits one species while leaving the other unaffected?',
    options: [
      { id: 'A', text: 'Mutualism' },
      { id: 'B', text: 'Parasitism' },
      { id: 'C', text: 'Commensalism' },
      { id: 'D', text: 'Amensalism' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Biology',
    chapter: 'Ecology & Environment',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 9000,
  },
  {
    id: 'q-bi-13',
    type: 'MCQ',
    questionText: 'Which disease is caused by the deficiency of vitamin D in children?',
    options: [
      { id: 'A', text: 'Scurvy' },
      { id: 'B', text: 'Rickets' },
      { id: 'C', text: 'Beriberi' },
      { id: 'D', text: 'Pellagra' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Biology',
    chapter: 'Nutrition & Health',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 8000,
  },
  {
    id: 'q-bi-14',
    type: 'MCQ',
    questionText: 'What is the end product of anaerobic glycolysis in human skeletal muscle during intense exercise?',
    options: [
      { id: 'A', text: 'Ethanol and CO₂' },
      { id: 'B', text: 'Lactic acid' },
      { id: 'C', text: 'Acetyl-CoA' },
      { id: 'D', text: 'Citric acid' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Biology',
    chapter: 'Respiration in Organisms',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 7000,
  },
  {
    id: 'q-bi-15',
    type: 'MCQ',
    questionText: 'Which class of immunoglobulins is the most abundant in human blood plasma?',
    options: [
      { id: 'A', text: 'IgA' },
      { id: 'B', text: 'IgM' },
      { id: 'C', text: 'IgG' },
      { id: 'D', text: 'IgE' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Biology',
    chapter: 'Human Health & Disease',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 6000,
  },
  {
    id: 'q-bi-16',
    type: 'MCQ',
    questionText: 'Where does the Calvin cycle (light-independent reactions of photosynthesis) take place inside chloroplasts?',
    options: [
      { id: 'A', text: 'Thylakoid membrane' },
      { id: 'B', text: 'Stroma' },
      { id: 'C', text: 'Lumen' },
      { id: 'D', text: 'Outer membrane' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Biology',
    chapter: 'Photosynthesis',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 5000,
  },
  {
    id: 'q-bi-17',
    type: 'MCQ',
    questionText: 'Which structure connects muscle to bone in the human musculoskeletal system?',
    options: [
      { id: 'A', text: 'Ligament' },
      { id: 'B', text: 'Tendon' },
      { id: 'C', text: 'Cartilage' },
      { id: 'D', text: 'Fascia' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Biology',
    chapter: 'Locomotion & Movement',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 4000,
  },
  {
    id: 'q-bi-18',
    type: 'MCQ',
    questionText: 'Which kingdom of Whittaker’s five-kingdom classification includes unicellular prokaryotic organisms?',
    options: [
      { id: 'A', text: 'Protista' },
      { id: 'B', text: 'Monera' },
      { id: 'C', text: 'Fungi' },
      { id: 'D', text: 'Plantae' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Biology',
    chapter: 'Biological Classification',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 3000,
  },
  {
    id: 'q-bi-19',
    type: 'MCQ',
    questionText: 'What is the role of bile produced by the liver in human digestion?',
    options: [
      { id: 'A', text: 'Enzymatic digestion of starch' },
      { id: 'B', text: 'Emulsification of dietary lipids' },
      { id: 'C', text: 'Digestion of proteins into peptides' },
      { id: 'D', text: 'Absorption of vitamin B12' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Biology',
    chapter: 'Digestion',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 2000,
  },
  {
    id: 'q-bi-20',
    type: 'MCQ',
    questionText: 'What is the start codon in mRNA for translation in almost all living organisms?',
    options: [
      { id: 'A', text: 'UAA' },
      { id: 'B', text: 'AUG' },
      { id: 'C', text: 'UGA' },
      { id: 'D', text: 'UAG' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Biology',
    chapter: 'Molecular Genetics',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 1000,
  },

  // Mathematics (15 Questions)
  {
    id: 'q-ma-1',
    type: 'MCQ',
    questionText: 'What is the derivative of f(x) = sin(x) with respect to x?',
    options: [
      { id: 'A', text: '-cos(x)' },
      { id: 'B', text: 'cos(x)' },
      { id: 'C', text: 'tan(x)' },
      { id: 'D', text: '-sin(x)' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Mathematics',
    chapter: 'Calculus',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 500,
  },
  {
    id: 'q-ma-2',
    type: 'MCQ',
    questionText: 'What is the value of the definite integral of e^(2x) dx from x = 0 to x = 1?',
    options: [
      { id: 'A', text: '(e² - 1) / 2' },
      { id: 'B', text: 'e² - 1' },
      { id: 'C', text: '2(e² - 1)' },
      { id: 'D', text: 'e² / 2' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Mathematics',
    chapter: 'Definite Integrals',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 400,
  },
  {
    id: 'q-ma-3',
    type: 'MCQ',
    questionText: 'If a matrix A is of order 3x3 with determinant det(A) = 4, what is det(2A)?',
    options: [
      { id: 'A', text: '8' },
      { id: 'B', text: '16' },
      { id: 'C', text: '32' },
      { id: 'D', text: '64' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Mathematics',
    chapter: 'Matrices and Determinants',
    difficulty: 'hard',
    active: true,
    createdAt: Date.now() - 300,
  },
  {
    id: 'q-ma-4',
    type: 'MCQ',
    questionText: 'What is the sum of the interior angles of a convex hexagon (6 sides)?',
    options: [
      { id: 'A', text: '540°' },
      { id: 'B', text: '720°' },
      { id: 'C', text: '900°' },
      { id: 'D', text: '1080°' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Mathematics',
    chapter: 'Geometry',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 250,
  },
  {
    id: 'q-ma-5',
    type: 'MCQ',
    questionText: 'What is the probability of rolling a sum of 7 with two standard fair 6-sided dice?',
    options: [
      { id: 'A', text: '1/12' },
      { id: 'B', text: '1/6' },
      { id: 'C', text: '5/36' },
      { id: 'D', text: '7/36' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Mathematics',
    chapter: 'Probability',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 200,
  },
  {
    id: 'q-ma-6',
    type: 'MCQ',
    questionText: 'What is the value of limit as x approaches 0 of sin(x) / x?',
    options: [
      { id: 'A', text: '0' },
      { id: 'B', text: '1' },
      { id: 'C', text: 'Infinity' },
      { id: 'D', text: 'Undefined' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Mathematics',
    chapter: 'Limits & Continuity',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 180,
  },
  {
    id: 'q-ma-7',
    type: 'MCQ',
    questionText: 'In a right triangle, if the hypotenuse is 13 cm and one leg is 5 cm, what is the length of the other leg?',
    options: [
      { id: 'A', text: '10 cm' },
      { id: 'B', text: '11 cm' },
      { id: 'C', text: '12 cm' },
      { id: 'D', text: '8 cm' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Mathematics',
    chapter: 'Trigonometry & Pythagoras',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 160,
  },
  {
    id: 'q-ma-8',
    type: 'MCQ',
    questionText: 'What is the 10th term of the arithmetic progression (AP): 3, 7, 11, 15, ...?',
    options: [
      { id: 'A', text: '36' },
      { id: 'B', text: '39' },
      { id: 'C', text: '43' },
      { id: 'D', text: '40' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Mathematics',
    chapter: 'Sequences & Series',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 140,
  },
  {
    id: 'q-ma-9',
    type: 'MCQ',
    questionText: 'What is the solution set to the quadratic equation x² - 5x + 6 = 0?',
    options: [
      { id: 'A', text: 'x = 2, 3' },
      { id: 'B', text: 'x = -2, -3' },
      { id: 'C', text: 'x = 1, 6' },
      { id: 'D', text: 'x = -1, -6' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Mathematics',
    chapter: 'Quadratic Equations',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 120,
  },
  {
    id: 'q-ma-10',
    type: 'MCQ',
    questionText: 'What is the dot product of two perpendicular vectors in 3D Euclidean space?',
    options: [
      { id: 'A', text: '1' },
      { id: 'B', text: '0' },
      { id: 'C', text: '-1' },
      { id: 'D', text: 'Magnitude product' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Mathematics',
    chapter: 'Vector Algebra',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 100,
  },
  {
    id: 'q-ma-11',
    type: 'MCQ',
    questionText: 'What is log₁₀(1000)?',
    options: [
      { id: 'A', text: '1' },
      { id: 'B', text: '2' },
      { id: 'C', text: '3' },
      { id: 'D', text: '10' },
    ],
    correctAnswer: 'C',
    marks: 1,
    subject: 'Mathematics',
    chapter: 'Logarithms',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 90,
  },
  {
    id: 'q-ma-12',
    type: 'MCQ',
    questionText: 'What is the sum of roots for the polynomial 2x² - 8x + 5 = 0?',
    options: [
      { id: 'A', text: '-4' },
      { id: 'B', text: '4' },
      { id: 'C', text: '2.5' },
      { id: 'D', text: '-2.5' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Mathematics',
    chapter: 'Polynomials',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 80,
  },
  {
    id: 'q-ma-13',
    type: 'MCQ',
    questionText: 'What is the radius of the sphere represented by x² + y² + z² = 49?',
    options: [
      { id: 'A', text: '49' },
      { id: 'B', text: '7' },
      { id: 'C', text: '14' },
      { id: 'D', text: '3.5' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Mathematics',
    chapter: '3D Geometry',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 70,
  },
  {
    id: 'q-ma-14',
    type: 'MCQ',
    questionText: 'How many distinct permutations are there of the letters in the word "TEST"?',
    options: [
      { id: 'A', text: '24' },
      { id: 'B', text: '12' },
      { id: 'C', text: '6' },
      { id: 'D', text: '4' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Mathematics',
    chapter: 'Permutations & Combinations',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 60,
  },
  {
    id: 'q-ma-15',
    type: 'MCQ',
    questionText: 'What is the value of cos²(theta) + sin²(theta) for any real angle theta?',
    options: [
      { id: 'A', text: '0' },
      { id: 'B', text: '1' },
      { id: 'C', text: '-1' },
      { id: 'D', text: 'tan²(theta)' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Mathematics',
    chapter: 'Trigonometric Identities',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 50,
  },

  // Computer Science & Logic (9 Questions - brings total to exactly 100 questions!)
  {
    id: 'q-cs-1',
    type: 'MCQ',
    questionText: 'What is the worst-case time complexity of standard Merge Sort on an array of n elements?',
    options: [
      { id: 'A', text: 'O(n)' },
      { id: 'B', text: 'O(n log n)' },
      { id: 'C', text: 'O(n²)' },
      { id: 'D', text: 'O(log n)' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Computer Science',
    chapter: 'Data Structures & Algorithms',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 40,
  },
  {
    id: 'q-cs-2',
    type: 'MCQ',
    questionText: 'Which data structure follows the Last-In, First-Out (LIFO) order of operation?',
    options: [
      { id: 'A', text: 'Queue' },
      { id: 'B', text: 'Stack' },
      { id: 'C', text: 'Binary Search Tree' },
      { id: 'D', text: 'Heap' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Computer Science',
    chapter: 'Data Structures',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 35,
  },
  {
    id: 'q-cs-3',
    type: 'MCQ',
    questionText: 'What is the binary representation of decimal integer 25?',
    options: [
      { id: 'A', text: '11001' },
      { id: 'B', text: '10101' },
      { id: 'C', text: '11100' },
      { id: 'D', text: '10011' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Computer Science',
    chapter: 'Digital Logic & Number Systems',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 30,
  },
  {
    id: 'q-cs-4',
    type: 'MCQ',
    questionText: 'In relational database design, what does ACID stand for?',
    options: [
      { id: 'A', text: 'Atomicity, Consistency, Isolation, Durability' },
      { id: 'B', text: 'Accuracy, Concurrency, Indexing, Data' },
      { id: 'C', text: 'Automated, Clustered, Integrated, Distributed' },
      { id: 'D', text: 'Access, Control, Interface, Dependency' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Computer Science',
    chapter: 'Database Management',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 25,
  },
  {
    id: 'q-cs-5',
    type: 'MCQ',
    questionText: 'Which network layer in the OSI reference model is responsible for logical routing of packets?',
    options: [
      { id: 'A', text: 'Data Link Layer' },
      { id: 'B', text: 'Network Layer' },
      { id: 'C', text: 'Transport Layer' },
      { id: 'D', text: 'Physical Layer' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Computer Science',
    chapter: 'Computer Networks',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 20,
  },
  {
    id: 'q-cs-6',
    type: 'MCQ',
    questionText: 'What boolean logic gate produces an output 0 ONLY when both of its inputs are 1?',
    options: [
      { id: 'A', text: 'AND' },
      { id: 'B', text: 'NAND' },
      { id: 'C', text: 'NOR' },
      { id: 'D', text: 'XOR' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Computer Science',
    chapter: 'Digital Electronics',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 15,
  },
  {
    id: 'q-cs-7',
    type: 'MCQ',
    questionText: 'In object-oriented programming, which principle allows subclasses to provide specific implementations of methods defined by their parent class?',
    options: [
      { id: 'A', text: 'Polymorphism' },
      { id: 'B', text: 'Encapsulation' },
      { id: 'C', text: 'Composition' },
      { id: 'D', text: 'Delegation' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Computer Science',
    chapter: 'OOP Concepts',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 10,
  },
  {
    id: 'q-cs-8',
    type: 'MCQ',
    questionText: 'What is the primary function of an operating system’s memory management unit (MMU)?',
    options: [
      { id: 'A', text: 'Translate virtual addresses to physical memory addresses' },
      { id: 'B', text: 'Execute CPU instructions directly' },
      { id: 'C', text: 'Compress hard drive sectors' },
      { id: 'D', text: 'Manage network socket interfaces' },
    ],
    correctAnswer: 'A',
    marks: 1,
    subject: 'Computer Science',
    chapter: 'Operating Systems',
    difficulty: 'medium',
    active: true,
    createdAt: Date.now() - 5,
  },
  {
    id: 'q-cs-9',
    type: 'MCQ',
    questionText: 'In cryptography, what type of key is shared publicly in asymmetric encryption systems such as RSA?',
    options: [
      { id: 'A', text: 'Private Key' },
      { id: 'B', text: 'Public Key' },
      { id: 'C', text: 'Session Key' },
      { id: 'D', text: 'Pre-shared symmetric secret' },
    ],
    correctAnswer: 'B',
    marks: 1,
    subject: 'Computer Science',
    chapter: 'Cryptography & Security',
    difficulty: 'easy',
    active: true,
    createdAt: Date.now() - 1,
  },
];

// Demo Tests
export const DEMO_TESTS: Test[] = [
  {
    id: 'test-active-chem',
    name: 'CHEM-101 Chemistry Comprehensive Exam',
    description: 'Weekly assessment covering chemical bonding, thermodynamics, equilibrium, and assertion-reason analysis.',
    durationMinutes: 40,
    startTime: Date.now() - 60 * 60 * 1000, // started 1 hour ago
    endTime: Date.now() + 24 * 60 * 60 * 1000, // active for 24 hours
    totalQuestions: 40,
    assertionReasonCount: 5,
    mcqCount: 35,
    positiveMarks: 1,
    marksPerQuestion: 1,
    negativeMarkingEnabled: true,
    negativeMarks: 0.25,
    negativeMarking: 0.25,
    allowUnanswered: true,
    randomizeQuestions: true,
    randomizeOptions: true,
    maxAttempts: 1,
    accessCode: 'CHEM-7X92',
    status: 'active',
    createdBy: DEMO_TEACHER.id,
    createdAt: Date.now() - 2 * 86400000,
  },
  {
    id: 'test-completed-phys',
    name: 'PHYS-201 Mechanics & Waves Evaluation',
    description: 'Mid-term evaluation of kinematics, dynamics, circular motion, and wave principles.',
    durationMinutes: 30,
    startTime: Date.now() - 48 * 60 * 60 * 1000,
    endTime: Date.now() - 24 * 60 * 60 * 1000, // closed yesterday
    totalQuestions: 40,
    assertionReasonCount: 5,
    mcqCount: 35,
    positiveMarks: 1,
    marksPerQuestion: 1,
    negativeMarkingEnabled: true,
    negativeMarks: 0.25,
    negativeMarking: 0.25,
    allowUnanswered: true,
    randomizeQuestions: true,
    randomizeOptions: true,
    maxAttempts: 1,
    accessCode: 'PHYS-4M21',
    status: 'closed',
    createdBy: DEMO_TEACHER.id,
    createdAt: Date.now() - 5 * 86400000,
  },
];

// Seeded student submissions for test-completed-phys to enable instant rich analytics and export testing
export const DEMO_ATTEMPTS: TestAttempt[] = [
  {
    id: 'att-1',
    testId: 'test-completed-phys',
    studentId: 'stu-1',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav@testifyme.edu',
    questionIds: DEMO_QUESTIONS.slice(0, 40).map(q => q.id),
    questions: [],
    answers: {},
    score: 36.25,
    maxScore: 40,
    correctCount: 37,
    incorrectCount: 3,
    unansweredCount: 0,
    percentage: 90.6,
    startedAt: Date.now() - 36 * 3600 * 1000,
    expiresAt: Date.now() - 36 * 3600 * 1000 + 30 * 60 * 1000,
    submittedAt: Date.now() - 36 * 3600 * 1000 + 26 * 60 * 1000,
    status: 'submitted',
  },
  {
    id: 'att-2',
    testId: 'test-completed-phys',
    studentId: 'stu-2',
    studentName: 'Maya Patel',
    studentEmail: 'maya@testifyme.edu',
    questionIds: DEMO_QUESTIONS.slice(0, 40).map(q => q.id),
    questions: [],
    answers: {},
    score: 32.5,
    maxScore: 40,
    correctCount: 34,
    incorrectCount: 6,
    unansweredCount: 0,
    percentage: 81.3,
    startedAt: Date.now() - 35 * 3600 * 1000,
    expiresAt: Date.now() - 35 * 3600 * 1000 + 30 * 60 * 1000,
    submittedAt: Date.now() - 35 * 3600 * 1000 + 28 * 60 * 1000,
    status: 'submitted',
  },
  {
    id: 'att-3',
    testId: 'test-completed-phys',
    studentId: 'stu-3',
    studentName: 'Liam Chen',
    studentEmail: 'liam@testifyme.edu',
    questionIds: DEMO_QUESTIONS.slice(0, 40).map(q => q.id),
    questions: [],
    answers: {},
    score: 28.75,
    maxScore: 40,
    correctCount: 31,
    incorrectCount: 9,
    unansweredCount: 0,
    percentage: 71.9,
    startedAt: Date.now() - 34 * 3600 * 1000,
    expiresAt: Date.now() - 34 * 3600 * 1000 + 30 * 60 * 1000,
    submittedAt: Date.now() - 34 * 3600 * 1000 + 29 * 60 * 1000,
    status: 'submitted',
  },
  {
    id: 'att-4',
    testId: 'test-completed-phys',
    studentId: 'stu-4',
    studentName: 'Sophia Davis',
    studentEmail: 'sophia@testifyme.edu',
    questionIds: DEMO_QUESTIONS.slice(0, 40).map(q => q.id),
    questions: [],
    answers: {},
    score: 38.75,
    maxScore: 40,
    correctCount: 39,
    incorrectCount: 1,
    unansweredCount: 0,
    percentage: 96.9,
    startedAt: Date.now() - 33 * 3600 * 1000,
    expiresAt: Date.now() - 33 * 3600 * 1000 + 30 * 60 * 1000,
    submittedAt: Date.now() - 33 * 3600 * 1000 + 24 * 60 * 1000,
    status: 'submitted',
  },
  {
    id: 'att-5',
    testId: 'test-completed-phys',
    studentId: 'stu-5',
    studentName: 'Rohan Gupta',
    studentEmail: 'rohan@testifyme.edu',
    questionIds: DEMO_QUESTIONS.slice(0, 40).map(q => q.id),
    questions: [],
    answers: {},
    score: 24.5,
    maxScore: 40,
    correctCount: 27,
    incorrectCount: 10,
    unansweredCount: 3,
    percentage: 61.3,
    startedAt: Date.now() - 32 * 3600 * 1000,
    expiresAt: Date.now() - 32 * 3600 * 1000 + 30 * 60 * 1000,
    submittedAt: Date.now() - 32 * 3600 * 1000 + 30 * 60 * 1000,
    status: 'submitted',
  },
  {
    id: 'att-6',
    testId: 'test-completed-phys',
    studentId: 'stu-6',
    studentName: 'Lucas Walker',
    studentEmail: 'lucas@testifyme.edu',
    questionIds: DEMO_QUESTIONS.slice(0, 40).map(q => q.id),
    questions: [],
    answers: {},
    score: 19.25,
    maxScore: 40,
    correctCount: 23,
    incorrectCount: 15,
    unansweredCount: 2,
    percentage: 48.1,
    startedAt: Date.now() - 31 * 3600 * 1000,
    expiresAt: Date.now() - 31 * 3600 * 1000 + 30 * 60 * 1000,
    submittedAt: Date.now() - 31 * 3600 * 1000 + 29 * 60 * 1000,
    status: 'submitted',
  },
  {
    id: 'att-7',
    testId: 'test-completed-phys',
    studentId: 'stu-7',
    studentName: 'Emma Watson',
    studentEmail: 'emma@testifyme.edu',
    questionIds: DEMO_QUESTIONS.slice(0, 40).map(q => q.id),
    questions: [],
    answers: {},
    score: 34.0,
    maxScore: 40,
    correctCount: 35,
    incorrectCount: 4,
    unansweredCount: 1,
    percentage: 85.0,
    startedAt: Date.now() - 30 * 3600 * 1000,
    expiresAt: Date.now() - 30 * 3600 * 1000 + 30 * 60 * 1000,
    submittedAt: Date.now() - 30 * 3600 * 1000 + 25 * 60 * 1000,
    status: 'submitted',
  },
  {
    id: 'att-8',
    testId: 'test-completed-phys',
    studentId: 'stu-8',
    studentName: 'Ethan Taylor',
    studentEmail: 'ethan@testifyme.edu',
    questionIds: DEMO_QUESTIONS.slice(0, 40).map(q => q.id),
    questions: [],
    answers: {},
    score: 30.0,
    maxScore: 40,
    correctCount: 32,
    incorrectCount: 8,
    unansweredCount: 0,
    percentage: 75.0,
    startedAt: Date.now() - 29 * 3600 * 1000,
    expiresAt: Date.now() - 29 * 3600 * 1000 + 30 * 60 * 1000,
    submittedAt: Date.now() - 29 * 3600 * 1000 + 27 * 60 * 1000,
    status: 'submitted',
  },
];
